title: Jashanjot Singh
email: s_jashan@encs.concordia.ca
description: |
  Jashanjot Singh, Concordia University
  Montreal, QC, Canada
baseurl: "" 
url: "jashanj0tsingh.github.io" 
twitter_username: _jashanjotsingh
github_username:  jashanj0tsingh

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Global Variables
user:
  name: Jashanjot Singh
  status: Actively looking for internships!
  description: Currently pursuing MSc. Computer Science at Concordia University

# pages
page_names:
  - home
  - about

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/